### ISSUE TITLE
Exception with CJK characters

### ISSUE THREAD

**Issue by webcpp** [karastojko/mailio#1]
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  context: asio.ssl error

**Comment by karastojko** [comment]
Hi,
Can you please share more details regarding the environment, protocol you are using, code that made the exception?

**Comment by webcpp** [comment]
if a string use utf8 encoding and it contain CJK characters then the application throw the exception.

**Comment by karastojko** [comment]
Can you please paste the code snippet here?

**Comment by webcpp** [comment]
I write a method to send some maiil,but the application always throw the error:
`context: asio.ssl error`
code: 
```cpp
std::string smtps_send_mail(const std::string& host, int port, const std::string& user, const std::string& password, const std::string& from, const std::string& to, const std::string& subject, const std::string& content) {
            std::string error;
            try {
                mailio::message message;
                message.header_codec(mailio::message::header_codec_t::BASE64);
                message.sender(mailio::mail_address(from, from));
                message.add_recipient(mailio::mail_address(to, to));
                message.subject(subject);
                message.content_transfer_encoding(mailio::mime::content_transfer_encoding_t::QUOTED_PRINTABLE);
                message.content_type(mailio::message::media_type_t::TEXT, "plain", "utf-8");
                message.content(content);
                mailio::smtps smtp_server(host, port);
                smtp_server.authenticate(user, password, mailio::smtps::auth_method_t::LOGIN);
                smtp_server.submit(message);

            } catch (mailio::smtp_error& e) {
                error = e.what();
            } catch (mailio::dialog_error& e) {
                error = e.what();
            } catch (mailio::codec_error & e) {
                error = e.what();
            } catch (std::exception& e) {
                error = e.what();
            }
            return error;
        }
```

**Comment by karastojko** [comment]
Can you please add the subject/message with CJK characters you are trying to send? Since the error is on Asio.SSL level, did you install Boost with OpenSSL?

**Comment by webcpp** [comment]
I use a template engine and some template pages to create string content,these template pages contain some CJK characters.
When the application sends mail,it throw the exception sometimes,
but this is not always the case.
I have installed boost and openssl.
Thank you for your reply.
Maybe it's not a question of libmailio, it's my misuse.

**Comment by karastojko** [comment]
If the mail server allows, you might try plain (no SSL) connection to see if the error still happens.

**Comment by webcpp** [comment]
Thanks.
