### ISSUE TITLE
Missing file export.hpp 

### ISSUE THREAD

**Issue by Kintawesar** [karastojko/mailio#101]
linux redhat
GCC 10.3.1

I'm successfully compiled library from master sources, but I can't compile an example because of missing ```export.hpp``` in library headers  On other versions get the same problem.

```
mailio/codec.hpp:24:10: fatal error: export.hpp: No such file or directory
   24 | #include "export.hpp"
      |          ^~~~~~~~~~~~
```

**Comment by karastojko** [comment]
So, the existing examples do not compile or you cannot compile your own example?

**Comment by Kintawesar** [comment]
Sorry, that is my bad - I didn't do ```make install``` but just copied library and headers, so my own example didn't work.
After ```make install``` all works fine.
Maybe do specify in documentation about generated ```export.hpp``` and need of ```make install``` ?

**Comment by karastojko** [comment]
In the Linux section of the installation procedure it says `make install` in the last step. The file `export.hpp`  is not intended to be public, so I woukd rather not mention it in the documentation.
