### ISSUE TITLE
How to generate now a shared library

### ISSUE THREAD

**Issue by mr-j0nes** [karastojko/mailio#102]
Hello,

I was using an older version of the library (2019) with no problem. At the time, when building, it was generating a shared library by default.
Now I upgraded to the latest tag 0.21.0 and it only builds a static library. The option MAILIO_BUILD_SHARED_LIBRARY described in the README does not seem to work anymore..
Even the master version does not do it. Am I missing something?

Thanks in advance.

**Comment by karastojko** [comment]
Sorry for this break, it was made as part of the effort to add *mailio* to Vcpkg. Just modify this line in the `CmakeLists.txt`:
```
add_library(${PROJECT_NAME} SHARED ${project_sources} ${project_headers})
```
(note the additional "shared" flag). Thanks for pointing out, I will update the documentation and maybe check if it's required at all for the Vcpkg port.
