### ISSUE TITLE
Horizontal tabs in header bodies

### ISSUE THREAD

**Issue by ostermal** [karastojko/mailio#104]
Hi! First of all, thanks for this great library.

Working with it, I've noticed that while the code works fine for most emails, trying to receive some messages will always cause the following exception while the library is processing the message's headers:
`Format failure of the header value '<value>'.`

Looking into this issue, I found out that the root cause for this is horizontal tab characters `\t` which are part of the header value. Simply adding horizontal tabs to the regex `HEADER_VALUE_REGEX` in `mime.cpp` did indeed solve the issue for me.

So I wondered if the problematic emails might be incorrectly formatted, but according to [RFC 5322](https://datatracker.ietf.org/doc/html/rfc5322#section-2.2) horizontal tabs are explicitly allowed in header values:
> A field body may be composed of printable US-ASCII characters
   as well as the space (SP, ASCII value 32) and horizontal tab (HTAB,
   ASCII value 9) characters (together known as the white space
   characters, WSP).

Am I mistaken or should tabs then be added to the allowed characters, at least in the value part of headers?

**Comment by karastojko** [comment]
Hi,
Can you please provide an example of such header? I tried quickly few ones but I had no problems.

**Comment by ostermal** [comment]
This is the format of the header I encountered the problems with:
```
Received: from SRV2-test@sender.com
 (srv2-test@sender.com [192.168.245.16])	by
 smtp-01.test@sender.com (Postfix) with ESMTP id 8D16C3CE	for
 <test@receiver.com>; Sat,  20 Aug 2022 11:01:35 +0200
 (CEST)
```
There is a tab character before the "by" and the "for". When I add the `\t` to the allowed characters (`HEADER_VALUE_REGEX`), without any other modifications, everything works as expected.

**Comment by karastojko** [comment]
Should be fixed with the latest commit. I have added you to the Contributors section. Thanks for the fix.
