### ISSUE TITLE
Reserved identifiers

### ISSUE THREAD

**Issue by canyone2015** [karastojko/mailio#108]
**INTERNATIONAL STANDARD ISO/IEC 14882:2020(E) Programming languages — C++ Sixth edition 2020-12-ISO (2020)**
5.10 Identifiers [lex.name]
3 In addition, **some identifiers are reserved for use by C++ implementations and shall not be used otherwise**; no diagnostic is required.
3.1 Each identifier that contains a double underscore `__` or begins with an underscore followed by an uppercase letter is reserved to the implementation for any use.
3.2 Each identifier that begins with an underscore is reserved to the implementation for use as a name in the global namespace.

Recommendation: rename variables containing at least one underscore at the beginning of the name.
For example, in classes: `field_` or `m_field`.

**Comment by karastojko** [comment]
Thanks, I should do it.

**Comment by karastojko** [comment]
It should be fixed with the last few commits.
