### ISSUE TITLE
SMTPS Switching to SSL failed

### ISSUE THREAD

**Issue by AdamGoris** [karastojko/mailio#109]
I am trying to send a simple test message using smtp as is outlined in the README, and I'm running into an issue.

My code is:
```
message msg;
mail_address from = mail_address("sender", "MY_EMAIL");
mail_address to = mail_address("receiver", "MY_EMAIL2");

msg.from(from);
msg.add_recipient(to);
msg.subject("Test");
msg.content("Hello there");

smtps conn("smtp.gmail.com", 587);
conn.authenticate("MY_EMAIL", "MY_PASSWORD", smtps::auth_method_t::LOGIN);

std::string send_result = conn.submit(msg);
```
and the error I am receiving is: 
```
terminate called after throwing an instance of 'mailio::dialog_error'
  what():  Switching to SSL failed.
```
Which occurs when attempting to authenticate.

Does anyone know what would be causing this error?
Any help will be greatly appreciated.

**Comment by karastojko** [comment]
As [described](https://developers.google.com/gmail/imap/imap-smtp), the port 465 is for TLS and 587 for STARTTLS. Thus, use either
```
smtps conn("smtp.gmail.com", 465);
conn.authenticate("MY_EMAIL", "MY_PASSWORD", smtps::auth_method_t::LOGIN);
```
or
```
smtps conn("smtp.gmail.com", 587);
conn.authenticate("MY_EMAIL", "MY_PASSWORD", smtps::auth_method_t::START_TLS);
```
Let me know if this helps.

Cheers

**Comment by AdamGoris** [comment]
Thanks for the response, I can now connect to the smtp server, but when I try to send a message, using `conn.submit(msg);`, I get the error:
```
terminate called after throwing an instance of 'mailio::smtp_error'
  what():  Mail sender rejection.
```
Do I have to set something up to allow my email address to send via smtp?

**Comment by karastojko** [comment]
1. Is the authentication email same as the sender email?
2. Do you have enabled 2FA for that email account?

**Comment by AdamGoris** [comment]
1. Yes sender and auth email are the same
2. No 2FA on the account

**Comment by karastojko** [comment]
Can you please add printing of the received line in the case of failing? So, something like
```
    if (std::get<1>(tokens) && !positive_completion(std::get<0>(tokens)))
    {
        std::cout << std::get<2>(tokens) << std::endl;
        throw smtp_error("Mail sender rejection.");
    }
```
in the `smtp.cpp:88-89`, then recompile _mailio_, start the example again and paste here the result (remove the sensitive info if any). (Obviously I have to add better error reporting in this case.)

**Comment by AdamGoris** [comment]
I wasn't able to add this line and recompile as I built using vcpkg and it was over complicated trying to rebuild.
But I did setup nodemailer in node.js and was able to figure out how to setup my gmail account to allow it to send via smtp.

Essentially, gmail disabled low security sign in and now you have to enable 2FA and create an app password:
https://stackoverflow.com/a/45479968/15003926

After doing this I am no longer getting the Mail sender rejection error.
