### ISSUE TITLE
Issue Building

### ISSUE THREAD

**Issue by Machtor** [karastojko/mailio#113]
Hello,

I am trying to build mailio, but it is my first time ever using github. I am having difficulties trying to understand how to do all this on my own. I am sorry if this is not the place to ask. 

Here is my issue. I am currently on Windows 10, so I have gotten Cmake installed, Boost installed, and OpenSSL installed. However, every time I try to build mailio I keep getting this error: 

----------------------------------------------------------------------------------------------

-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/msys64/mingw64/bin/cc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/msys64/mingw64/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at C:/Program Files/CMake/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: system date_time regex) (found version
  "1.71.0")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.24/Modules/FindBoost.cmake:2376 (find_package_handle_standard_args)
  CMakeLists.txt:60 (find_package)

----------------------------------------------------------------------------------------------

As you may see, it says it found Boost version 1.71.0. However, an error still occurs. I was wondering if maybe I installed something wrong.

Please send any information on what I can do to fix any of this.

**Comment by karastojko** [comment]
What is the exact cmake command you have executed? Is Boost built statically or dynamically?

**Comment by Machtor** [comment]
Hello,

Thank you very much for responding. However, I just went ahead and installed Vcpkg. It made the process way easier. 

The cmake command I used went like this:

cmake.exe -G "MinGW Makefiles" ..

I will go ahead and close this issue. Thank you again for the response.
