### ISSUE TITLE
smtps_attachment.cpp wont work

### ISSUE THREAD

**Issue by boomer11111111** [karastojko/mailio#114]
Been trying to use the "smtps_attachment.cpp", but i just cant get this to work. Tried everything i could. The following line is the one responsible for the error from what i can tell:

atts.push_back(make_tuple(std::ref(ifs1), string("aleph0.png"), message::content_type_t(message::media_type_t::IMAGE, "png")));

 more specifically the content_type_t function. If i comment that line out it works, but obvisously the email that is sent, does not include the attached aleph0.png. Looks like a linker error maybe but i dont even know anymore :( . I have done all the linking i think, and as i said the rest works just fine. Any help is greatly appreciated. Below is the error message:

error LNK2019: unresolved external symbol "public: __cdecl mailio::mime::content_type_t::content_type_t(enum mailio::mime::media_type_t,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (??0content_type_t@mime@mailio@@QEAA@W4media_type_t@12@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z) referenced in function main

**Comment by karastojko** [comment]
Did you fetch mailio from Vcpkg or from Github?

**Comment by boomer11111111** [comment]
I installed mailio with vcpkg, in the instructions it said it was an option.

**Comment by karastojko** [comment]
It is the option. I recall there was a problem on Windows with linking, it was fixed by exporting the needed types, `content_type` was one of them.
So, your version is 0.21.0 which is the latest on Vcpkg?

**Comment by boomer11111111** [comment]
Not gonna lie, i have to find out how to see vcpkg version. Also i m not sure what "it was fixed by exporting the needed types" means. (I am extremely grateful for the responses btw)

**Comment by karastojko** [comment]
I mean mailio 0.21.9, not Vcpkg. 
By exporting I mean - does your version of `mime.hpp` has the `MAILIO_EXPORT` like [here](https://github.com/karastojko/mailio/blob/10c6bedfaeee209801ae0872cd0c4161099b8fb1/include/mailio/mime.hpp#L74) ?

**Comment by boomer11111111** [comment]
I checked mailio version and it says "0.20.0#1", so there is that.  Also in my mime.hpp i see MAILIO_EXPORT class like in your link, but i dont see MAILIO_EXPORT struct in it. (I uninstalled and reinstalled mailio today, how do i get 0.21.0 version?)

**Comment by karastojko** [comment]
I have just installed mailio by Vcpkg from scratch and I have the version 0.21.0 (can be seen within the file `version.hpp`). You are getting the version 0.20.0?

**Comment by boomer11111111** [comment]
Yes, in my version.hpp it says:

#define MAILIO_VERSION_MAJOR 0
#define MAILIO_VERSION_MINOR 20
#define MAILIO_VERSION_PATCH 0

And i reinstalled today and did update package (if i did it right), but still got 0.20.0#1 (not sure what that #1 is but its there).

**Comment by karastojko** [comment]
I did with Vcpkg on both Windows and Linux, the version 0.21.0 is taken. I have no explanation what is going on your setup. Maybe you could try to pull from Github and compile with Cmake.

**Comment by boomer11111111** [comment]
I have only heard of Cmake, not sure what it is or does. Any other way to install, manually maybe?

**Comment by boomer11111111** [comment]
OK OK FIXED IT. I did a git pull and re-run the bootstrap-vcpkg.bat file, but this time (magically) mailio has the right version. Thanks a lot for the help (like im actually grateful).

**Comment by karastojko** [comment]
Good to hear. If the linker error disappears now, then I guess the issue can be closed.

**Comment by boomer11111111** [comment]
Yes yes close it.
