### ISSUE TITLE
Documentation of auth_method_t

### ISSUE THREAD

**Issue by gekrap** [karastojko/mailio#118]
Can the different possible values of `<protocol>::auth_method_t` be documented? 
I'm quite confused. It seems to mix different config options, namely transport security and authentication method.
How do the individual options correspond to RFCs?

**Comment by karastojko** [comment]
Hopefully the comments from the latest [commit](https://github.com/karastojko/mailio/commit/9e001b2815c6fd4b5d89fae9f83de546d4e93c52) give more sense to the authentication methods.

**Comment by gekrap** [comment]
Yes, it clarifies things a bit. Enough for me right now.
