### ISSUE TITLE
Question about ranges (imap::messages_range_t)

### ISSUE THREAD

**Issue by gekrap** [karastojko/mailio#121]
Is there a possibility to have a range of `imap::messages_range_t` include the maximum sequence number without having to know it? [RFC9051](https://www.ietf.org/rfc/rfc9051.html#section-4.1.1) allows the special character "*" for this case. Can I use this via mailio?

**Comment by karastojko** [comment]
Does this solve your problem:
```
imaps conn("xxx", 993);
conn.authenticate("xxx", "xxx", imaps::auth_method_t::LOGIN);
conn.select(list<string>({"Inbox"}));
list<unsigned long> messages;
conn.search(list<imap::search_condition_t>({imap::search_condition_t(imap::search_condition_t::SID_LIST, list<imap::messages_range_t>{make_pair(100, std::nullopt)})}), messages, true);
```
Note the `nullopt` for the criteria you have asked.
