### ISSUE TITLE
Add vcpkg manifest support

### ISSUE THREAD

**Issue by tsurumi-yizhou** [karastojko/mailio#129]
Using vcpkg to automatically install the dependencies.

I had tried to deal with it but failed. I found it too difficult for me to understand the CMakeLists.txt. With several errors, the CMakeLists.txt may be supposed to remake.

**Comment by karastojko** [comment]
I do not understand. Do you have a problem installing the library over Vcpkg?

**Comment by tsurumi-yizhou** [comment]
What I mean is to add automatic dependency installation to the project by adding a new vcpkg.json. However, it seems that you don't think it's necessary.

**Comment by karastojko** [comment]
But it's there in the Vcpkg [ports](https://github.com/microsoft/vcpkg/pull/23696/files). Ok, I need to add the latest version 0.22, but there exists the manifest within the Vcpkg.
