### ISSUE TITLE
IMAP(Switching to SSL failed.)

### ISSUE THREAD

**Issue by YZJClear** [karastojko/mailio#131]
vcpkg: mailio[core]:x64-windows-static -> 0.21.0#2

code:
mailio::imaps conn("com", 143);
conn.authenticate("user", "pwd", mailio::imaps::auth_method_t::LOGIN);
exception:
Switching to SSL failed.

**Comment by karastojko** [comment]
Are you sure that the port 143 is with TLS? By default, it is the non-TLS port.

**Comment by YZJClear** [comment]
my fault, i should be use mailio::imap, not mailio::imaps
