### ISSUE TITLE
send imap quoted string

### ISSUE THREAD

**Issue by yjm6560** [karastojko/mailio#134]
hi.
i had searched imap c++ library, and this library is very helpful.
but i found a point which could be improved.

# imap quoted string in LOGIN command
string can be quoted string like following pictures in [rfc3501](https://www.rfc-editor.org/rfc/rfc3501#section-9) grammar.
<img width="367" alt="image" src="https://github.com/karastojko/mailio/assets/49180520/6b698859-a4ef-43fd-8deb-33866d270cbf">
<img width="517" alt="image" src="https://github.com/karastojko/mailio/assets/49180520/d9eba445-dcde-4227-89ff-dfaebd65492f">

And userid and password containing `"` or `\` In `LOGIN` command must be quoted string not plain string.
if not, imap server can't parse the imap request.
To be more specific, if password contains imap reserved character like `(`, `)`, `{`, `}`, imap server can't distinguish whether it is imap reserved character or part of password string.
and if password contains space, server would be confused.
So it will be safer to make userid and password into imap quoted string.

the way to convert plain string to imap quoted string is simple.
Just put `\` in front of quoted-special characters(`"` and `\` ), and cover it with dquote(`"`).
e.g.
```
// AS-IS : imap server can't parse it
1 LOGIN userid" passwd\
// TO-BE
1 LOGIN "userid\"" "passwd\\"
```

Please feel free to tell me if I made a mistake.
thank you.

**Comment by yjm6560** [comment]
i will post other points which can be improved in a few days, if you don't mind..

**Comment by karastojko** [comment]
Thank you for the valuable suggestions. Let me play a little bit with the code, and I will apply the changes.

**Comment by yjm6560** [comment]
Also, I think it would be good to consider using imap quoted string in the imap commands which uses the mailbox name.
same problem can be occurred in mailbox name.

**Comment by karastojko** [comment]
Login [now](https://github.com/karastojko/mailio/commit/c524e5f7a958da0cfb0dff20e792424b60deb2dd) uses the quoted string on login. I will check the same for the mailbox name.

**Comment by karastojko** [comment]
Quoted string for the folder names are also [added](https://github.com/karastojko/mailio/commit/67e077e6f39fded7e3d191b2583bb3cf0041acfb). Seems that Zoho is not happy with a folder which contains the double quote in it's name.

**Comment by yjm6560** [comment]
67e077e commit seems that you removed DQUOTE surrounding folder name.
i thought same way with c524e5f should be applied to folder name.

did you test folder name like `test("aaa")`, `test)]`, `test"aaa`??
i haven't tested after 67e077e commit but i think it may not work well..

**Comment by karastojko** [comment]
I think you are right, the last change was not good, I'll have to do it in a better way.

**Comment by karastojko** [comment]
Let's see if this [time](https://github.com/karastojko/mailio/commit/63e91bb1617420cf21d9a4a16b4522184bdd4036) is better.

**Comment by yjm6560** [comment]
> Let's see if this [time](https://github.com/karastojko/mailio/commit/63e91bb1617420cf21d9a4a16b4522184bdd4036) is better.

it seems to work well!
there would be no work with imap quoted string if #136 is done!

There may be people who converts id,passwd and folder name to imap quoted string themselves. Therefore, it would be good to write it down in the release note that they don't have to do it themselves.
