### ISSUE TITLE
Please, could anyone provide me an example of how to get the mail content as a unencoded string?

### ISSUE THREAD

**Issue by nigoolasi** [karastojko/mailio#140]
Please, could anyone provide me an example of how to get the mail content as a unencoded string?
when i use the code below
`msg.format(msgbody)`

i get an string encoded by base64,

**Comment by yjm6560** [comment]
is `msgbody` original mime?
if so, i think `msg.parse(msgbody); std::cout << msg.content();` can help.
if it doesn't work, do `msgbody = "\r\n" + msgbody` and try again

**Comment by karastojko** [comment]
The answer seems correct to me.
