### ISSUE TITLE
Is it ok to use `-std=c++17` instead of `-std=gnu++1z`

### ISSUE THREAD

**Issue by orchistro** [karastojko/mailio#142]
Hi, 

I am using two compilers: gcc and bullseye.
Bullseye does not support gnu extensions, it supports ISO c++ standard only, while gcc supports (of course😁) `-std=gnu++1z`.

BTW, according to the [cmake documentation](https://cmake.org/cmake/help/latest/prop_tgt/CXX_EXTENSIONS.html#prop_tgt:CXX_EXTENSIONS), the`CXX_EXTENSIONS` property is `ON` by default. It makes `-std=gnu++1z` be passed to bullseye, which I don't want to.

I wonder if it is ok to add `set(CMAKE_CXX_EXTENSIONS OFF)` to the `CMakeLists.txt`.
Is any gnu c++ extension required ?

EDIT:
Since mailio supports many platforms, it should use only ISO standard c++.
I think `set(CMAKE_CXX_EXTENSIONS OFF)` line should be added to the `CMakeLists.txt`. What do you think?

Regards.

**Comment by karastojko** [comment]
Thanks for the remark. I have merged the PR and added you to the list of contributors. If you are familiar with the Chinese, you can also create PR to translate the sentence in English regarding your contribution in the [readme file](https://github.com/karastojko/mailio/blob/master/README_zh.md).
