### ISSUE TITLE
How to handle the  inline image in the mime data?

### ISSUE THREAD

**Issue by lofonder** [karastojko/mailio#158]
How to handle the  mime of  inline format .the html file contained the image file with src="cid:logo.png",is there any good ideas to handle this data?
Do I need to replace the cid:logo file with using regrex?

By the way,cause there're so many formats of the mime which not unstandard.Such as multipart/alternative contained the text only.So is there any simply and easier way to handle these datas so that I could see the whole message without lossing any parts of the mime?

**Comment by karastojko** [comment]
Can you please provide me an example? Does this [issue](https://github.com/karastojko/mailio/issues/139) relate to your problem?
