### ISSUE TITLE
issue on message.content()

### ISSUE THREAD

**Issue by mikemasam** [karastojko/mailio#16]
Hi, 
i can't read content sent from gmail account to gmail imap server, i get empty string, 
on this line
`std::cout << data << std::endl;`

```
`mailio::imaps *conn = new mailio::imaps(this->imap_host, this->imap_port);

      conn->authenticate(this->account_mail, this->account_password, mailio::imaps::auth_method_t::LOGIN);
      mailio::message msg;
msg.line_policy(mailio::codec::line_len_policy_t::NONE);
conn->fetch("inbox", new_index, msg);
      std::cout << msg.subject() << std::endl;
      std::string data = msg.content();
      std::cout << "size of =" << sizeof(data) << std::endl;
      msg.parse(data);
      std::cout << data << std::endl;
      delete conn;`
```

**Comment by karastojko** [comment]
Hi.
It's hard to say by not having the exact message. `imap::fetch()` internally calls `message::parse()`, so there is no need to call it again. What is the length of `data` after the content is read? Does your message have attachments? Subject is read without problems?

Regards,

**Comment by mikemasam** [comment]
Thanks for the reply, 
i added parse for testing only.
Length is always 20 or 22 return of sizeof.
Message has no attachments.
Subject is there without any problem.

also when i use my own mail server, everything works fine, but when i use gmail server, no content,

my code [https://github.com/mikemasam/mailsam/blob/master/src/mail/imap.cpp](url)

**Comment by karastojko** [comment]
Do you have 2FA turned on for Gmail? There is an instruction for that case in Readme file.

**Comment by mikemasam** [comment]
it's not turned on, i double checked that.
i can give you access to the email if you.

**Comment by karastojko** [comment]
If you have nothing confidential in the mailbox, I could try the same. Or you can attach here the original message, so I could execute internal test for the message format only.

**Comment by mikemasam** [comment]
Delivered-To: alltoall07@gmail.com
Received: by 2002:ac9:18a6:0:0:0:0:0 with SMTP id z38csp3590493ocd;
        Sun, 13 Jan 2019 14:18:02 -0800 (PST)
X-Received: by 2002:a24:784a:: with SMTP id p71mr7546933itc.158.1547417882105;
        Sun, 13 Jan 2019 14:18:02 -0800 (PST)
ARC-Seal: i=1; a=rsa-sha256; t=1547417882; cv=none;
        d=google.com; s=arc-20160816;
        b=Z1pgLzj0oXh8kS/gnNpe7IDU7l1JNcB2a2muqJiyoyHmO+ol6BMIRCCUl9Yr4lXNnz
         T9Ndh8L8NHtcFkqCWa/J2QPo6b9w7Yf7dnd1FYw1x3X/chHLNCKeBJGyVdJj/TyVhPqH
         m6MkDjWbPGAv8dUJDwWw/JUUwxqHqGLkyV0IZQb6LnPLd+H9YLz1DN+TECTnS3C925pj
         /PS3XIuBZ4BDhauvw7Qd6XwUL6ntSmD7U1S+wsaOtbFwgKYNJZmnKxfGQUn0iVHJu7A7
         FXP5AtLxHpNqErBBiBvOt4m8naHOFEXxoNXhfOBpn+JwdG2OlI7tyHyc1YDddw3mG5vy
         gwEQ==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=to:subject:message-id:date:from:mime-version:dkim-signature;
        bh=5Ai5LdmSzNHCHJjusUDOh5k8EFw5tAe3QL1/CThBDvA=;
        b=CkrOwAU36/QLBAdg1XNU/HGW0CtKRicUxOHT12wTh2pkWTUH/t20seD67U7Lt8Gy8F
         8LhQsDe1CReDu/tRhlZdlWNKF3cHZ2QJ675L0vZwqnjOy3vtDmnUq+KoxLveMsvZVDXw
         0upQ+gi32U6arM9Vexmpt+4DMYaBW/OfqxVKklKJMyZKu9a56ZPzvDnH5HMsW6fRpuil
         EzpoD3DT1+x4RY5LBxjhG+CcYk4TIgK7Q68vDjJY0MS1S/61ckXFdH8IrMDHcAuflqwk
         t4qoYv4BauqnDkyWoBYcVs0lqJ0UnO6+jD0Z8ffPIQJPkHT5iFi6sGEkrlj2R0FevqQT
         BvKg==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@gmail.com header.s=20161025 header.b=CPtWBvPN;
       spf=pass (google.com: domain of meshackmasam@gmail.com designates 209.85.220.41 as permitted sender) smtp.mailfrom=meshackmasam@gmail.com;
       dmarc=pass (p=NONE sp=QUARANTINE dis=NONE) header.from=gmail.com
Return-Path: <meshackmasam@gmail.com>
Received: from mail-sor-f41.google.com (mail-sor-f41.google.com. [209.85.220.41])
        by mx.google.com with SMTPS id l188sor13327758itb.33.2019.01.13.14.18.02
        for <alltoall07@gmail.com>
        (Google Transport Security);
        Sun, 13 Jan 2019 14:18:02 -0800 (PST)
Received-SPF: pass (google.com: domain of meshackmasam@gmail.com designates 209.85.220.41 as permitted sender) client-ip=209.85.220.41;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@gmail.com header.s=20161025 header.b=CPtWBvPN;
       spf=pass (google.com: domain of meshackmasam@gmail.com designates 209.85.220.41 as permitted sender) smtp.mailfrom=meshackmasam@gmail.com;
       dmarc=pass (p=NONE sp=QUARANTINE dis=NONE) header.from=gmail.com
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20161025;
        h=mime-version:from:date:message-id:subject:to;
        bh=5Ai5LdmSzNHCHJjusUDOh5k8EFw5tAe3QL1/CThBDvA=;
        b=CPtWBvPN6QwaLMspvlXsdIDtJkqjWO7RoUil+RmdMt37T+zs9C1zIr196Y5AYRA5mM
         l9XGAnie1OyeaibHVcqcDn+z1o2wqN6dcvUCuGLxNcStTwilo7uH1AF9/usuI0rgJ0vg
         5r3g6wbTDy4tCxLV86n4/mvRb+4yUDn4NuhvubSMa3HGZzMVrck+ZXjo5VnHIzOJrR81
         nRb4d+K6rKHFH7Ybp8pvUEMG0MfBa9Ag83GfrW5nz6xO2vrTwBnQEADh1FUXF1NWbcHs
         9vrUqSCvjFTqk1uvrF+91dWKVTMNtAoggAwi5I60PBoz98ECcuQhVq4vslfNxvj38Muc
         jlhg==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:mime-version:from:date:message-id:subject:to;
        bh=5Ai5LdmSzNHCHJjusUDOh5k8EFw5tAe3QL1/CThBDvA=;
        b=Yzf+d0jYqObWosn/mdd3vvANtW31WlJAV8mTN9PGdd/SGVd/430+WBWA6+akFpil28
         rLGoFcYJPoAgRIvB774Q5BF6cIcUVrxM6hnifC+IWnkjJEGBPuZ/mGw7zNq3jaVH/5v4
         J3A0262HBK5ZftWJvPYW4pNK87unHsNuPvqEWlJDorrlFpp51dTVkGaC2kvtJevW+otz
         PwsKpA65H8CJgtZd0C/n5z7Yczc8gyKlS08kXElEWZylJOjLp7gcCNSmrIURqj50Jo+l
         f06uRDP/uCkFFr+dNRDIIek3VWhcZB6puSXezm6Evku3jybNCWFESKDnbzfRs1RvFNVR
         dzew==
X-Gm-Message-State: AJcUukcFLJrZ3kBfXQXvb2yW/bom0x7WZNw2OoMIDWDJT6jg2Jmi8J6V K5Q5pRSECC0wXUghYgkk6hwX4aZEXr0nyzMS+gci1Q==
X-Google-Smtp-Source: ALg8bN69jA0NTTIpU5LGeN0ztdMfws/aCwz7dS6IPqtR2UZ1eIvtVHhR71Jxcj88LHbW777kPQzo82wNeeYNNWhbmYM=
X-Received: by 2002:a24:b518:: with SMTP id v24mr7249225ite.159.1547417881672; Sun, 13 Jan 2019 14:18:01 -0800 (PST)
MIME-Version: 1.0
From: "Masam M." <meshackmasam@gmail.com>
Date: Mon, 14 Jan 2019 01:17:50 +0300
Message-ID: <CAO_MoJCgoVVGXuOifg8terL0UYj21kj3spyU3tSY_y9t0vLJww@mail.gmail.com>
Subject: Test 4
To: coder Alltoall <alltoall07@gmail.com>
Content-Type: multipart/alternative; boundary="0000000000002803e6057f5e4db2"

--0000000000002803e6057f5e4db2
Content-Type: text/plain; charset="UTF-8"

Testing 4 and the last one

--0000000000002803e6057f5e4db2
Content-Type: text/html; charset="UTF-8"

<div dir="auto">Testing 4 and the last one</div>

--0000000000002803e6057f5e4db2--

**Comment by karastojko** [comment]
This is a multipart message (available within the content typr), and thus you should access its parts by using `std::vector<mime> mime::parts() const;`. In your case, you should print the first part with `cout << msg.parts().at(0).content() << endl;`. Let me know if this resolves your issue.

**Comment by mikemasam** [comment]
Awesome.
This code is working now, i get even the html emails.
```
  if(msg.content_type().type == mailio::mime::media_type_t::MULTIPART){
      for (mailio::mime _msg: msg.parts()) {  
        std::string data = _msg.content();
        std::cout << data << std::endl;
      }
    }else if (msg.content_type().type == mailio::mime::media_type_t::TEXT){
        std::string data = msg.content();
        std::cout << data << std::endl;
    }
```
One last thing.
Should i expect content to be on 

> parts().at(0)

 always or should i just loop and concatenate every message to one big string.?

**Comment by karastojko** [comment]
It is the vector of MIME parts, so you should iterate to fetch them all. Each MIME part can contain other MIME parts, i.e. they are defined recursively.

**Comment by mikemasam** [comment]
Thanks, all is well now.
[https://github.com/mikemasam/mailsam/commit/a8f31a78fa4cc3abc25ea0ab146001572946ad48](https://github.com/mikemasam/mailsam/commit/a8f31a78fa4cc3abc25ea0ab146001572946ad48)
