### ISSUE TITLE
problem with static library version

### ISSUE THREAD

**Issue by boomer11111111** [karastojko/mailio#161]
I have a working program that can send an email with an attachment with no problems, using "multi-threaded debug dll" option.

But, when i run the exact same code with "multi-threaded debug", the code does compile and the program does run, but crashes and does not work (screenshot of the crash error window is included here incase it helps).

I also want to mention that i have installed both the default version of the mailio library, and the static one.

I have found that this line here is causing the problem, as the program runs without crashing when i comment it out. The line is the following:

conn.authenticate("xxxxxxxxxxxxxx@gmail.com", "xxxxxxxxxxxx", smtps::auth_method_t::LOGIN);

![Rec118_036](https://github.com/karastojko/mailio/assets/117929325/cb77be93-b295-4aba-abb5-aa36a7174851)

Thanks a lot in advance.

**Comment by karastojko** [comment]
Does it also happen with the `smtps_attachment.cpp` example?

**Comment by boomer11111111** [comment]
That is what i am using, i just got the code from smtps_attachment.cpp. Maybe i am doing something wrong with the linking.

How do i use static library of mailio? I mean how do i link it? Do i need to build a mailio.lib somehow?

Thanks for the response.

**Comment by boomer11111111** [comment]
Ok im not sure what was wrong exactly, but i had not linked the mailio library in the right way for sure, so probably that was the reason.
