### ISSUE TITLE
error when linking statically

### ISSUE THREAD

**Issue by boomer11111111** [karastojko/mailio#162]
mailio.lib(message.cpp.obj) : error LNK2019: unresolved external symbol __std_find_trivial_1 referenced in function "char const * __cdecl __std_find_trivial<char const ,char>(char const *,char const *,char)" (??$__std_find_trivial@$$CBDD@@YAPEBDPEBD0D@Z)

I get the error you see above, when trying to link statically.

I was getting many similar errors about "libcrypto.lib", but when i added Crypt32.lib in Properties->Linker->Input->Additional Dependencies those errors went away, and i am just left with the error you see above.

Is there some .lib i need to add like i did with Crypt32.lib ?

(Also i did a git pull and vcpkg upgrade today so everything is up-to-date.)

Thanks in advance.

**Comment by karastojko** [comment]
The libraries I link in Visual Studio:
```
mailio.lib
libboost_system-vc142-mt-x64-1_81.lib
libboost_date_time-vc142-mt-x64-1_81.lib
libboost_regex-vc142-mt-x64-1_81.lib
ssleay32MD.lib
libeay32MD.lib
```
