### ISSUE TITLE
It looks like a problem with the SSL verification.

### ISSUE THREAD

**Issue by boomer11111111** [karastojko/mailio#163]
It looks like a problem with the SSL verification.
In the version 0 23 I have imposed the stronger SSL verification by default, which seems to be too much for many email servers. It is fixed in the latest versions. If you still want to stay on 0.23 then you have to change the SSL options by using `smtps::ssl_options()` with the value `dialog::ssl_options_t::verify_none`.
Let me know whether it fixes the problem.

_Originally posted by @karastojko in https://github.com/karastojko/mailio/issues/148#issuecomment-1850034861_

**Comment by boomer11111111** [comment]
How do you do that, i mean what is the line exactly, because i cant figure it out.

**Comment by karastojko** [comment]
Try something like
```
mailio::dialog_ssl::ssl_options_t opts = { boost::asio::ssl::context::sslv23, boost::asio::ssl::verify_none };
conn.ssl_options(opts);
```
