### ISSUE TITLE
Line policy overflow in a header (mime.cpp)

### ISSUE THREAD

**Issue by Displacer** [karastojko/mailio#166]
There is a condition for line.length() in mime.cpp parse_by_line function:

    if (line.length() > string::size_type(decoder_line_policy_))
        throw mime_error("Line policy overflow in a header.");

decoder_line_policy_ is set to mailio::codec::line_len_policy_t::RECOMMENDED which equals 73.

In some cases MS Exchange mail server produces lines with larger size, leading to exception thrown.

Can this value be increased to support such messages?

**Comment by Displacer** [comment]
setting codition to mailio::codec::line_len_policy_t::MANDATORY seems fixing this problem

**Comment by karastojko** [comment]
Correct, that's the purpose of the line policy.

**Comment by Displacer** [comment]
> Correct, that's the purpose of the line policy.

I have provided pull request https://github.com/karastojko/mailio/pull/167 to quick merge if this is correct changes.

PS: There is also pull request to support boost versions before 1.81 (Ubuntu 22.04 LTS have 1.74)

**Comment by Displacer** [comment]
It seems decoder_line_policy_ should be set for  mailio::codec::line_len_policy_t::MANDATORY in class initialization since there are overflows in mailio::bit8::decode (line 80) in some cases with RECOMMENDED value.

**Comment by Displacer** [comment]
there seems to be a problem in imap.cpp (line 458): msg.line_policy(line_policy, line_policy); 
the second parameter of msg.line_policy seems should be RECOMMENDED also

**Comment by Nullarity** [comment]
I have the same issue. In my case, the IMAP server is ionos.com. So, to fix it, I need to modify the source and build the project, right? Right now, I am using vcpkg for this library.

**Comment by Displacer** [comment]
> I have the same issue. In my case, the IMAP server is ionos.com. So, to fix it, I need to modify the source and build the project, right? Right now, I am using vcpkg for this library.

 You probably could try something like this in client code without rebuilding library:

 message msg;
 msg.line_policy(codec::line_len_policy_t::MANDATORY, codec::line_len_policy_t::MANDATORY);
 conn.fetch(msg_uid, msg);
 
I hope this will help.

**Comment by karastojko** [comment]
That's right. There is also the NONE policy which means unlimited.

**Comment by Nullarity** [comment]
Thank you, guys, it helped, but unfortunately, while fetching other emails, I get SIGSEGV.

Stack Trace:
 boost::iterators::transform_iterator<boost::algorithm::detail::to_lowerF<char>, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, boost::use_default, boost::use_default>::dereference() const transform_iterator.hpp:130
 boost::iterators::transform_iterator<boost::algorithm::detail::to_lowerF<char>, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, boost::use_default, boost::use_default>::reference boost::iterators::iterator_core_access::dereference<boost::iterators::transform_iterator<boost::algorithm::detail::to_lowerF<char>, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, boost::use_default, boost::use_default>>(boost::iterators::transform_iterator<boost::algorithm::detail::to_lowerF<char>, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, boost::use_default, boost::use_default> const&) iterator_facade.hpp:631
 boost::iterators::detail::iterator_facade_base<boost::iterators::transform_iterator<boost::algorithm::detail::to_lowerF<char>, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, boost::use_default, boost::use_default>, char, boost::iterators::random_access_traversal_tag, char, long, false, false>::operator*() const iterator_facade.hpp:737
 void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>::_M_construct<boost::iterators::transform_iterator<boost::algorithm::detail::to_lowerF<char>, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, boost::use_default, boost::use_default>>(boost::iterators::transform_iterator<boost::algorithm::detail::to_lowerF<char>, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, boost::use_default, boost::use_default>, boost::iterators::transform_iterator<boost::algorithm::detail::to_lowerF<char>, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, boost::use_default, boost::use_default>, std::input_iterator_tag) basic_string.tcc:172
 void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>::_M_construct_aux<boost::iterators::transform_iterator<boost::algorithm::detail::to_lowerF<char>, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, boost::use_default, boost::use_default>>(boost::iterators::transform_iterator<boost::algorithm::detail::to_lowerF<char>, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, boost::use_default, boost::use_default>, boost::iterators::transform_iterator<boost::algorithm::detail::to_lowerF<char>, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, boost::use_default, boost::use_default>, std::__false_type) basic_string.h:255
 void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>::_M_construct<boost::iterators::transform_iterator<boost::algorithm::detail::to_lowerF<char>, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, boost::use_default, boost::use_default>>(boost::iterators::transform_iterator<boost::algorithm::detail::to_lowerF<char>, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, boost::use_default, boost::use_default>, boost::iterators::transform_iterator<boost::algorithm::detail::to_lowerF<char>, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, boost::use_default, boost::use_default>) basic_string.h:274
 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>::basic_string<boost::iterators::transform_iterator<boost::algorithm::detail::to_lowerF<char>, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, boost::use_default, boost::use_default>, void>(boost::iterators::transform_iterator<boost::algorithm::detail::to_lowerF<char>, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, boost::use_default, boost::use_default>, boost::iterators::transform_iterator<boost::algorithm::detail::to_lowerF<char>, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, boost::use_default, boost::use_default>, std::allocator<char> const&) basic_string.h:641
 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> boost::algorithm::detail::transform_range_copy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, boost::algorithm::detail::to_lowerF<char>>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, boost::algorithm::detail::to_lowerF<char>) case_conv.hpp:122
 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> boost::algorithm::to_lower_copy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, std::locale const&) case_conv.hpp:79
 mailio::mime::content_type_t::operator=(mailio::mime::content_type_t const&) mime.cpp:78
 mailio::mime::operator=(mailio::mime&&) mime.hpp:171
 mailio::message::operator=(mailio::message&&) message.hpp:114
 mailio::imap::fetch(unsigned long, mailio::message&, bool, bool) imap.cpp:327

![image](https://github.com/user-attachments/assets/3f36e5d8-0465-4610-b3f8-6e371d0d6067)

**Comment by karastojko** [comment]
Thanks for the report. Can you please in the method `mime::content_type_t::operator=(const mime::content_type_t&)` before the line with `to_lower_copy` put printing of `cont_type.subtype` and paste the result here? I am interested to understand the reason of the crash of `to_lower_copy()` in your case.
