### ISSUE TITLE
the mime format problem

### ISSUE THREAD

**Issue by lofonder** [karastojko/mailio#170]
the 
**string_t mime::parse_header_value_attribute(const string& attr_value) const** 
only parsed the first line of the Content-Disposition

the mime data example:
`
Content-Type: application/pdf;

	name*0*=UTF-8''py%E5%8E%BF%E7%BA%A7%E6%9C%BA%E6%9E%84%E7%A7%91%E6%8A%80;

	name*1*=%9C%7D%E5%6A%A1%E9E7%BA%A7%E6%9C%BA%E6%9E%84%E7%E6%E6%8A%80.pdf

Content-Transfer-Encoding: base64

Content-Disposition: attachment;

	filename*0*=UTF-8''py%E5%8E%BF%E7%BA%A7%E6%9C%BA%E6%9E%84%E7%A7%91%E6%8A%80;

	filename*1*=%E5%9D%8D%E5%8C%E7%BA%A7%E6%9C%BA%E6%9E%84%E7%A7%91%E6%8A%80;

	filename*2*=pdf

`
the filename *1 and filename*2 was recoginzed as the url code.
is it a bug?

I think it would be better if decode the filename in the function of the mime::merge_attributes?
cause I founded that the filename*0* part was the nomal text decoded ,and  the filename*1* part was the text encoded.

**Comment by karastojko** [comment]
Let me check it.

**Comment by karastojko** [comment]
You  are right, there is a bug. I am fixing it...

**Comment by karastojko** [comment]
Please try the latest [commit](https://github.com/karastojko/mailio/commit/cf5ebd68d8ceb42880a59cec725f5b1d5e92fe13). It should fix your problem although it is still not complete by the [specification](https://datatracker.ietf.org/doc/rfc2231/).

**Comment by karastojko** [comment]
The percent codec is implemented now for both formatting and parsing.
