### ISSUE TITLE
parsing the mime format crashed

### ISSUE THREAD

**Issue by lofonder** [karastojko/mailio#178]
here is the mime data .
I couldnt find the bugs.
[test.txt](https://github.com/user-attachments/files/17164979/test.txt)

**Comment by karastojko** [comment]
Thanks for the report, let me try it.

**Comment by karastojko** [comment]
The last content type has the invalid zeroth name:
```
name*0*=UTF-8''%%E4%B8%AA%E4%BA%BA%B5%AE%A2%E6%88%B7%E4%B8%9A%E5%8A%A1%E5;
```
Double percent at the beginning is incorrect. Mailio 0.24.1 throws an exception, which is the desired behavior. Thus, I am closing the bug as already solved.

**Comment by lofonder** [comment]
sorry for that,may be its my mistake that encoding the Double percent.
In fact its not the wrong code here.i would show the realy faction next time.
