### ISSUE TITLE
Segmentation fault when sending more than one mail

### ISSUE THREAD

**Issue by mr-j0nes** [karastojko/mailio#21]
Hello there,

First of all this is a very nice piece of code. Thanks for sharing.

I am having a segmentation fault when sending more than one mail. For example if you modify the `smtps_simple_msg.cpp` to send two emails, you'll have the problem on the second submit().

The problem seems to be the constant:

`const local_time_facet* message::TIME_FACET = new local_time_facet("%a, %d %b %Y %H:%M:%S %q");`

when following line runs:

`ss.imbue(locale(ss.getloc(), TIME_FACET));`

the `std::locale` (according to the specs) deletes the allocated facet.  So then when running the second time the TIME_FACET  constant points to an already-deleted memory. address.

The obvious solution would be to create the facet every time:

`ss.imbue(locale(ss.getloc(), new local_time_facet("%a, %d %b %Y %H:%M:%S %q")));`

Let me know your thoughts.

Regards...

**Comment by karastojko** [comment]
You are right, the bug was introduced few days ago while refactoring. Please try the latest commit, sorry for the inconvenience.

**Comment by mr-j0nes** [comment]
Thanks for the quick reaction, now it works fine...
