### ISSUE TITLE
Question: SMTP vs SMTPS

### ISSUE THREAD

**Issue by mr-j0nes** [karastojko/mailio#22]
Hello there,

just a couple of questions, I am a bit confused about your naming convention for smtp and smtps. 
Isn't smtps deprecated like 15 years ago ?

You have the following:
smtp:::auth_method_t::NONE
smtp:::auth_method_t::LOGIN
smtps:::auth_method_t::NONE
smtp:s::auth_method_t::LOGIN
smtp:s::auth_method_t::START_TLS

what is the difference between the two NONEs and the two LOGINs. 

As I understand STARTTLS asks the server to upgrade the insecure connection to a secure one. So somehow it makes sense to me to have only one set of NONE, LOGIN and START_LS under a same nemespace..

**Comment by karastojko** [comment]
Hi,
One NONE is for SMTP the other for SMTPS, same for LOGIN. It would be more elegant to have enum inheritance, but that is not possible in C++.
There are still servers which use SMTPS, and it was easy to add - so there it is.

**Comment by mr-j0nes** [comment]
Thank you for the reply. I see. 
I guess then what confuses me is that START_TLS is not only a feature of SMTPS but also of SMTP. So why is it not available on SMTP too ?

**Comment by karastojko** [comment]
The idea is that `smtps` is for the secure type of connections. Since START_TLS is used to secure the connection, it is not available in `smtp`.

**Comment by mr-j0nes** [comment]
Ok I see now, thanks a lot.
