### ISSUE TITLE
Windows version crashes when timeout is not zero

### ISSUE THREAD

**Issue by ga2k** [karastojko/mailio#27]
Hi, I'm not sure what happened to the issue I logged last year, but it's gone now.

You confirmed a bug in the Windows version where if a timeout is specified for connect, a crash results. Have you gotten anywhere with this problem yet? No rush, just wondering...

**Comment by karastojko** [comment]
Hi,
I was debugging Windows crash and was able to reproduce it. but not to solve it. Since I could not spend a lot of time on that, no work was made. Hopefully in the following weeks I would be able to do some work on mailio.
Did you perhaps upgrade Boost?

**Comment by linuxpham** [comment]
Hi admin,
Your library is perfect.
But, if a timeout is specified for connecting, there is a crash result. (send_async - dialog.cpp).
My boost version is 1.6.7
Please fix it soon if you have time!
Thanks!

**Comment by karastojko** [comment]
Hi @linuxpham,
Can you please try the [fix](https://github.com/karastojko/mailio/compare/bug_74) and let me know if the issue is resolved? So far I tested it only on Linux and it seems it works in my case.

**Comment by linuxpham** [comment]
Hi @karastojko ,
It works!
Thank you so much!

**Comment by karastojko** [comment]
The fix is supposing to work on both Linux and Windows.

**Comment by linuxpham** [comment]
Thank you so much!
