### ISSUE TITLE
Wrong content_type_t when adding an attachment

### ISSUE THREAD

**Issue by david-antiteum** [karastojko/mailio#28]
If an email has content in HTML and then an attachment, the content losses the type.

- In message::attach it overwrites the attribute _content_type
- In message::format it sets the content as text/plain

**Comment by niclar** [comment]
@karastojko this is still an issue

**Comment by karastojko** [comment]
@niclar 
This PR is not merged because there was another issue not solved with this change. Did you try
`void attach(const std::istream&, const std::string&, media_type_t, const std::string&)`
or
`void attach(const std::list<std::tuple<std::istream&, std::string, content_type_t>>&)` ?

**Comment by niclar** [comment]
@karastojko  attach(const std::istream&, const std::string&, media_type_t, const std::string&) seems broken in my use case below. 
void attach(const std::list<std::tuple<std::istream&, std::string, content_type_t>>&) however seems to work. Thanks. 

```
msg.content_type(mailio::mime::content_type_t(mailio::mime::media_type_t::TEXT, "html", "utf-8"));
msg.content(content);
msg.content_transfer_encoding(mailio::mime::content_transfer_encoding_t::QUOTED_PRINTABLE);

//msg.attach(attachmentStream, attachmentName, mailio::mime::media_type_t::TEXT, "csv"); <--- destroys the content encoding above
msg.attach({{attachmentStream, attachmentName, mailio::mime::content_type_t(mailio::mime::media_type_t::TEXT, "csv", "utf-8")}});    

```

**Comment by karastojko** [comment]
@niclar 
The ` attach(const std::istream&, const std::string&, media_type_t, const std::string&)` is broken and will be deprecated. This PR is not closed since it contains the vcpkg port which will be included.

**Comment by niclar** [comment]
@karastojko  re vcpkg.  -I did a local one a while back.    -Can you expose static lib building something along the line of (or should I create a PR) ? ;

`vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
	OPTIONS
        -DMAILIO_BUILD_SHARED_LIBRARY:BOOL=OFF)`

**Comment by niclar** [comment]
-ah I see that this branch may address that as well.
 Awaiting the merge then. Great lib.

**Comment by david-antiteum** [comment]
@niclar have a look at #39

**Comment by david-antiteum** [comment]
OK, as the issue is fixed using void attach(const std::list<std::tuple<std::istream&, std::string, content_type_t>>&)  I will add a new PR just for vcpkg issues.
