### ISSUE TITLE
Custom headers

### ISSUE THREAD

**Issue by nicraMarcin** [karastojko/mailio#35]
I'd like to add custom header, for example `X-Mailer`.
I cannot find proper  method to do it.

How to add custom headers?

**Comment by karastojko** [comment]
Hi,
Unfortunately it is not possible to do it right now. Since it is not a big deal to add it (and I need it too), probably I'll do it in the next couple of weeks. Or if you are going to write the code, I can merge your PR.

**Comment by nicraMarcin** [comment]
Hi,
my c++ knowledge isn't so big, I'm beginner in this so I don't want to spoil something other, so I have to wait

**Comment by karastojko** [comment]
Please check the latest commit for this feature.
