### ISSUE TITLE
CMake version

### ISSUE THREAD

**Issue by triccyx** [karastojko/mailio#36]
On Ubuntu 20.04 the latest cmake version is 3.16.3.
Could you consider to change? 

```
 cmake_minimum_required (VERSION 3.16.4)
```
to
```
 cmake_minimum_required (VERSION 3.16.3)
```

**Comment by audaki** [comment]
The differences between 3.16.4 and 3.16.3 are negligible: https://blog.kitware.com/cmake-3-16-4-available-for-download/

**Comment by triccyx** [comment]
Yes, my question is about not forcing Ubuntu 20.04 users to upgrade with no reason the system.

**Comment by karastojko** [comment]
Sure, it does not make a difference to me. Please check the latest commit.

**Comment by triccyx** [comment]
Thanks!
