### ISSUE TITLE
Question - SMTP send exception

### ISSUE THREAD

**Issue by mohsenomidi** [karastojko/mailio#37]
Dear @karastojko 

Hope you are doing well, and thanks for your useful library. 

i am trying to use the SMTP send email the same as  `smtps_simple_msg.cpp`  and just change the  `smtps::auth_method_t` to LOGIN. 

and set the smtp address and credentials after the compiling i got this error : **Mail message rejection.**

I am trying to figure-out the problem and find these data and it maybe useful:

in below part of smtp.cpp the error returns : ( I Just print the error to get server message )  
```
   _dlg->send("DATA");
    line = _dlg->receive();
    tokens = parse_line(line);
    std::cout << "Receive :" << line << std::endl;
    if (!positive_intermediate(std::get<0>(tokens)))
        throw smtp_error("Mail message rejection.");
 ```

return value is: 250 HELP 
and because of HELP it throw the exception. 

just for more information I apply the same setting (ex: email address, smtp_server_address, authentication_method, ...)  in my gitlab test server and it works properly.

**Comment by mohsenomidi** [comment]
PS: i bypass the exception and the mail send successfully. ( I also receive the email ) 
but library return exception **Mail message rejection.** again
In the second part: 
```
    string msg_str;
    msg.format(msg_str, true);
    _dlg->send(msg_str + codec::CRLF + codec::DOT_CHAR);
    line = _dlg->receive();
    std::cout << "Receive 2 :" << line << std::endl;
    tokens = parse_line(line);
    if (!positive_completion(std::get<0>(tokens)))
        throw smtp_error("Mail message rejection.");
```
in this part the return value is : 334 VXNlc....

description of error code is :

`334   Response to the AUTH command when the requested security mechanism is accepted`

**Comment by karastojko** [comment]
Which port number you are using? 587 is usually for the STARTTLS while 465 is for TLS encrypted transport. You are switching from one to another authentication, thus I suspect you need to switch the port too.

**Comment by mohsenomidi** [comment]
i am using 465, and the LOGIN method :

Here is my code : 
```
int main()
{
    try
    {
        // create mail message
        message msg;
        msg.from(mail_address("test", "*********"));// set the correct sender name and address
        msg.add_recipient(mail_address("test", "**************"));// set the correct recipent name and address
        msg.subject("smtps simple message");
        msg.content("Hello, World!");

        // connect to server
        smtps conn("smtpurl*******", 465);
        // modify username/password to use real credentials
        conn.authenticate("***********USER", "*******Password", smtps::auth_method_t::LOGIN);
        cout << "Authenticated" << std::endl;
        conn.submit(msg);
        std::cout <<"Submitted" << std::endl;
    }
    catch (smtp_error& exc)
    {
        cout << exc.what() << endl;
    }
    catch (dialog_error& exc)
    {
        cout << exc.what() << endl;
    }

    return EXIT_SUCCESS;
}
```

this is my email server recommendation : 

Secure SSL/TLS Settings (Recommended) 

Password: | Use the email account’s password.
Outgoing Server: SMTP Port: 465
IMAP, POP3, and SMTP require authentication.

PS: my email server Certificate is not verified, self signed

**Comment by karastojko** [comment]
So, after the `DATA` command the server returns `250 HELP`? It should not, the RFC 5321 document in section 3.3 says `354 Intermediate reply` should be used. Can you please print the whole sequence of the commands and their replies within the `smtp::submit` method?

**Comment by mohsenomidi** [comment]
Yes this is the story happened, i will put log from scratch and will share output, also i will try with telnet to make the full test from smtp server and will share request/responses.

Just give me some hours to get access to my client again

Thanks for your kind response 🙏🙏

**Comment by mohsenomidi** [comment]
Dear @karastojko 

I create full log from all call stack in smtp.cpp The log structure is the like : 

CLASS_NAME:FUNCTION_NAME (OPERATION / SYNTAX) : DATA/RESPONSE

```
SMTP::SMTP Constructor (read_hostname()):development
SMTPS::AUTHENTICATE (auth_method_t::LOGIN)
SMTPS::SWITCH_TO_SSL Function
SMTP::CONNECT:220-host.com ESMTP Exim 4.92 #2 Tue, 18 Aug 2020 09:06:24 +0430
SMTP::EHLO (EHLO + _src_host):220-We do not authorize the use of this system to transport unsolicited,
SMTP::EHLO (while (!std::get<1>(tokens))):220 and/or bulk e-mail.
SMTP::AUTH_LOGIN (AUTH LOGIN):250-host.com Hello development [xxx.xx.xxx.xx]
SMTP::AUTH_LOGIN (SEND USERNAME):250-SIZE 52428800
SMTP::AUTH_LOGIN (SEND PASSWORD):250-8BITMIME
SMTP:SUBMIT (MAIL FROM):250-PIPELINING
SMTP:SUBMIT (LOOP RCPT TO):250-AUTH PLAIN LOGIN
SMTP:SUBMIT (DATA):250 HELP
Mail message rejection.
````
Test Result by openssl s_client :

```
$ openssl s_client -crlf -connect host.com:465
CONNECTED(00000003)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3

**[CUT OFF EXTRA LONG TEXT CERTIFICATE DATA]**

220-host.com ESMTP Exim 4.92 #2 Tue, 18 Aug 2020 08:31:33 +0430
220-We do not authorize the use of this system to transport unsolicited,
220 and/or bulk e-mail.

helo development
250 host.com Hello development [xxx.xx.xxx.xx]

ehlo development
250-host.com Hello development [xxx.xx.xxx.xx]
250-SIZE 52428800
250-8BITMIME
250-PIPELINING
250-AUTH PLAIN LOGIN
250 HELP

AUTH LOGIN
334 VXNlcm5hbWU6

Z2l0b*******c2QuY29t
334 UGFzc3dvcmQ6

cXdlY******TIzXw==
235 Authentication succeeded

mail from: <test@myemail.com>
250 OK

rcpt to: <myname@myemail.com>
250 Accepted

data
354 Enter message, ending with "." on a line by itself

test openssl
.

250 OK id=1k7stC-00CHyP-2P

```

It seems in multiple line return the received buffer can not be handled and corrupted,   
after successful connection, the server sends data in 3 lines and SMTP::CONNECT can not handle these 3 lines and the buffer keep all data and this buffer parsed in the next function call. (also same happened for EHLO)

**Comment by karastojko** [comment]
@mohsenomidi Thanks for the detailed log. Seems you are right. I will try to simulate the case you have and make a branch so you could also test it.

**Comment by mohsenomidi** [comment]
You are most welcome.
Okay, I will test it once you ask 🙏

**Comment by karastojko** [comment]
@mohsenomidi Can you please check if the [fix](https://github.com/karastojko/mailio/tree/bug_77) resolves the issue?

**Comment by karastojko** [comment]
Merged to the master branch, thanks a lot for the help.
