### ISSUE TITLE
Wrong mail header and contents on Ubuntu 20.04

### ISSUE THREAD

**Issue by triccyx** [karastojko/mailio#38]
When I try the simple example:
[example](https://github.com/karastojko/mailio/blob/master/examples/smtps_simple_msg.cpp)
 the mail is sent in a wrong way:
![Screenshot from 2020-08-17 23-05-16](https://user-images.githubusercontent.com/9121787/90444682-98d9e600-e0de-11ea-9dd6-6a22cd8d4dd8.png)
The screenshot is taken from Gmail. As you can see TO, SUBJECT, CONTENTS are all inserted in the FROM field. 
TO is also inserted into BCC (so the mail arrives).

Ubuntu 20.04
gcc 9.3.0
smtp is "smtp.gmail.com", 587

**Comment by karastojko** [comment]
It works fine in my case, also Ubuntu and Gmail. Is there a chance to test it with another mail server?

**Comment by karastojko** [comment]
@triccyx @RosenGeorgiev Please check the latest commit, it works for me in both static and dynamic linking.

**Comment by triccyx** [comment]
I have tested and it works for me.

**Comment by triccyx** [comment]
We can close this issue.
