### ISSUE TITLE
UB in static variables initialization

### ISSUE THREAD

**Issue by astepanov83** [karastojko/mailio#41]
`codec::CRLF` is initialized in codec.cpp
`mime::END_OF_LINE` is initialized in mime.cpp and depends on `codec::CRLF`
I exactly ran into a situation where `CRLF` was \r\n, but `END_OF_LINE` was empty

**Comment by karastojko** [comment]
@astepanov83 Please check the latest commit, it works for me in both static and dynamic linking.
