### ISSUE TITLE
mailio on conan

### ISSUE THREAD

**Issue by nicraMarcin** [karastojko/mailio#42]
@karastojko Hi, what do you think about add reciepe of mailio to [conan center](https://conan.io/center)?

**Comment by karastojko** [comment]
Hi,
It's a good idea. I'll try to do it within the version 0.21, together with vcpkg. For the current 0.20 I already have the list of features I would like to accomplish.

**Comment by nicraMarcin** [comment]
Hi @karastojko, when are you going to relase v 0.21?

**Comment by karastojko** [comment]
The plan is to finish the current v0.20 in December, and then I would start with the v0.21 which should deal with packaging and FreeBSD.

**Comment by mathbunnyru** [comment]
Thanks for this great library. It's exactly what I was needing.

Do you need some help with packaging this library for conan?
If you haven't started yet, I think I can help you with packaging it.

Not having conan package available is the only thing stopping me from using this library right now.

**Comment by karastojko** [comment]
Thanks for the offer. It would be great if you could add it. Then I could deal with the vcpkg as proposed before.
I am curious: why having no Conan package is stopping you from using mailio?

**Comment by mathbunnyru** [comment]
Because we're switching to conan when it's about external open source projects. It becomes much easier to maintain list of your dependencies, doesn't blow cmake lists, makes it available to almost any platform 

So, the strategy I'm using for the external dependencies is to first make them available through conan and then use them.

Yes, I will try to add you library, I have some experience creating new conan packages, should not be too difficult.

**Comment by mathbunnyru** [comment]
Started working on it.

https://github.com/conan-io/conan-center-index/pull/4017

I want to reduce patching to the minimum amount possible - this makes the recipe really nice and clean and generally improves the lib itself.
So I think I will create several PRs in this repository, then I will ask you to create a new version and add conan recipe for that version.

**Comment by mathbunnyru** [comment]
Submitted on review. I'm absolutely OK with a small patch I made.

**Comment by mathbunnyru** [comment]
@karastojko @nicraMarcin done!

https://conan.io/center/mailio

I added conan recipe for mailio 0.20.0.

Nothing needs to be done on your side.
Regarding the recipe, there is a small patch in cmake.

Full recipe is located here, updating versions is quite easy (especially if patch doesn't have to change):
https://github.com/conan-io/conan-center-index/tree/master/recipes/mailio

**Comment by karastojko** [comment]
@karastojko 
Many thanks, I have listed you in the Contributors section.
