### ISSUE TITLE
 INSTALL cannot find build/docs/html

### ISSUE THREAD

**Issue by ZanyScum** [karastojko/mailio#43]
> cmake ..

 gives me no warning or error.

> make install

 stops with the following error:

```
[100%] Built target pop3s_fetch_one
Install the project...
-- Install configuration: ""
CMake Error at cmake_install.cmake:41 (file):
  file INSTALL cannot find
  "/home/<username>/work/3rdParty/mailio/build/docs/html".

make: *** [Makefile:118: install] Error 1
```

**Comment by ZanyScum** [comment]
Btw, I am using Debian 10 stable

**Comment by ZanyScum** [comment]
If I execute
```
mkdir -p /home/<username>/work/3rdParty/mailio/build/docs/html
mkdir -p /home/<username>/work/3rdParty/mailio/build/docs/latex
```
and call
`make install`
with sudo 
`sudo make install`

then the script runs to the end. No idea what I am missing with the two empty directories.

**Comment by karastojko** [comment]
Hi,
Can you please try to run CMake with the `MAILIO_BUILD_DOCUMENTATION` turned off, to check if it's about the documentation generation?

**Comment by ZanyScum** [comment]
Yes, turning MAILIO_BUILD_DOCUMENTATION OFF made "sudo make install" run to the end without error.

As info, I did execute
`sudo apt-get install doxygen doxygen-doc graphviz libboost-all-dev libssl-dev`
but perhaps I need more doxygen packages to be able to create the documentation?

**Comment by karastojko** [comment]
You should have Doxygen installed, but since I do not use plain Debian I cannot say which exactly packages are required.
