### ISSUE TITLE
UTF-8 encoded Subject value causes exception

### ISSUE THREAD

**Issue by tsilia** [karastojko/mailio#49]
Hello.
Looks like a raw UTF-8 value of the `Subject` header causes an exception to be thrown, e.g.: `Format failure of the header value 'Тестовое письмо'` which happens when `mime::parse_header_name_value()` processes string `Subject: Тестовое письмо`

The `Issues` section of the main project page states that:
`Non-ASCII subject is assumed to be UTF-8`
which doesn't seem to be correct anymore as the `mime::parse_header_name_value()` method only checks if the value supplied matches `HEADER_VALUE_REGEX`.

**Comment by karastojko** [comment]
Hi,
Here is the test that I am using internally to test mailio (the subject in Russian cyrillic, the content in Serbian cyrillic):
```
BOOST_AUTO_TEST_CASE(proba)
{
    string msg_str = "From: mailio <mailio@alepho.com>\r\n"
        "To: mailio <mailio@alepho.com>\r\n"
        "Subject: =?UTF-8?B?0KLQtdGB0YLQvtCy0L7QtSDQv9C40YHRjNC80L4=?=\r\n"
        "Date: Sat, 26 Dec 2020 10:02:49 +0100\r\n"
        "MIME-Version: 1.0\r\n"
        "Content-Type: text/plain; charset=utf-8; format=flowed\r\n"
        "Content-Transfer-Encoding: 8bit\r\n"
        "Content-Language: en-US\r\n"
        "\r\n"
        "Ово је проба за ћирилицу.\r\n";
    message msg;

    ptime t = time_from_string("2016-02-11 22:56:22");
    time_zone_ptr tz(new posix_time_zone("+00:00"));
    local_date_time ldt(t, tz);
    msg.parse(msg_str);

    cout << msg.subject() << endl << msg.content() << endl;
    BOOST_CHECK(msg.subject() == "Тестовое письмо" && msg.content() == "Ово је проба за ћирилицу.");
}
```

It works in my case. Can you please paste here the email source here to check it?

**Comment by tsilia** [comment]
Hi, thank you for your reply.
I can see the difference now. Your `Subject` is additionally encoded. Mine is not:
```
Return-path: <bounce+035bef.490f3e9-user_name_=mailsrv.ru@mail.mail_srv2.ru>
Envelope-to: user_name_@mailsrv.ru
Delivery-date: Thu, 14 Nov 2019 15:38:04 +0000
Received: from m228-8.mailgun.net ([159.135.228.8]:26732)
	by mmxs.majordomo.ru with esmtps (TLS1.2:ECDHE_RSA_AES_128_GCM_SHA256:128)
	(Exim 4.90_1)
	(envelope-from <bounce+035bef.490f3e9-user_name_=mailsrv.ru@mail.mail_srv2.ru>)
	id 1iVHC7-0007NX-O3
	for user_name_@mailsrv.ru; Thu, 14 Nov 2019 15:38:03 +0000
Sender: noreply=mail_srv2.com@mail.mail_srv2.ru
Received: by mail_srv2.com (Postfix, from userid 33)
	id 67F5B3F7F8; Thu, 14 Nov 2019 18:31:06 +0300 (MSK)
To: user_name_@mailsrv.ru
Subject: Тестовое письмо
From: noreply@mail_srv2.com
Message-Id: <20191114153106.67F5B3F7F8@mail_srv2.com>
Date: Thu, 14 Nov 2019 18:31:06 +0300 (MSK)

Почта работает!
```
> The `Issues` section of the main project page states that:
> `Non-ASCII subject is assumed to be UTF-8`
So I assumed that raw UTF-8 without any additional encoding would be enough to treat `Subject` as UTF-8. But when my mail failed to parse I looked in the sources found this:
> which doesn't seem to be correct anymore as the `mime::parse_header_name_value()` method only checks if the value supplied matches `HEADER_VALUE_REGEX`.

So it must be that the main page statement regarding UTF-8 in `Subject` is not correct anymore.

**Comment by karastojko** [comment]
The MIME in mailio is 7bit, so anything beyond that has to be encoded. Under that assumption, everything not representable in 7bit has to be encoded, no matter if it's the header or the body. I will make that clear in the Readme file, thanks for the suggestion. I will take a look in the future of the 8bit MIME.
Also, thanks for the other PRs, I'll run the tests against them and merge them.

**Comment by tsilia** [comment]
Thank you for explanation. I should've probably name the issue "**Raw** UTF-8 encoded Subject ..." to avoid misunderstanding.
Also, could you please release your tests into the public, along with the source code? Well, at least those that don't use some private artifacts (passwords, etc). This would help in testing PRs prior to publishing them, and also could serve as a reference code or additional examples.

**Comment by karastojko** [comment]
I am considering somehow to publish tests, so I could use CI by GitHub. Definitely it would be easier for others to verify against their changes. For the mime/message I have tests without the credentials (still I would have to remove real mail addresses), so that should not be the problem. For the SMTP, POP3 and IMAP, I would have to move addresses and credentials to a private configuration file (if CI is providing something like that).

**Comment by karastojko** [comment]
@tsilia 
Perhaps the latest [commit](https://github.com/karastojko/mailio/commit/9b551f4177196235a4dde4d1dad87c7afb2c52cf) can help you with the 8bit encoding.

**Comment by tsilia** [comment]
Hey karastojko. Unfortunately I can't test it right now, but will galdly do when I have time.
Thanks for the fix!
