### ISSUE TITLE
make examples

### ISSUE THREAD

**Issue by elucterio** [karastojko/mailio#5]
Hello,
Thank you for your work !
In the makefile, to compile the examples, I needed to change the makefile to : 

$(EXAMPLES_BINS):
	test -d $(EXAMPLES_BUILD_DIR) || mkdir -p $(EXAMPLES_BUILD_DIR) $(CXX) $(CXX_FLAGS) $(INCS_DIR) $(LIBS_DIR) $(EXAMPLES_DIR)/$@.cpp -o $(EXAMPLES_BUILD_DIR)/$@ -L$(LIB_DIR) $(LD_FLAGS) -l$(PROJECT)

the librairies should go after the example.cpp

**Comment by karastojko** [comment]
Hi,
Thanks for using _mailio_.

Although I do not have such problem, you are probably right, libraries should go afterwards. At the moment, I am testing the proposed Autoconf/Automake scripts from the pull request, so hopefully the library will have soon fully featured build tool and problems like this one will go away.

Regards,
