### ISSUE TITLE
Empty values of 'References' and 'In-Reply-To' headers cause exceptions

### ISSUE THREAD

**Issue by tsilia** [karastojko/mailio#50]
Hello.
It seems that `References` and `In-Reply-To` headers are treated the same way as `Message-id` is: if the header has empty value or a value that can't be parsed as a correct one, an exception is thrown which prevents emails with such headers from getting fetched by the library. But using an empty string in these headers seems to be a common behaviour among mail clients/servers. I have few emails sent with MS Outlook which have empty `References`, `In-Reply-To` and even `Message-id` headers, e.g. (emphasis is mine):
>...
>References: 
>In-Reply-To: 
>Subject: =?koi8-r?B?UkU6IOvBzcXS2Q==?=
>Date: Mon, 9 Dec 2019 14:14:31 +0300
>Message-ID: <004101d5ae81$d43895b0$7ca9c110$@somedomain.tld>
>MIME-Version: 1.0
>Content-Type: multipart/alternative;
>	boundary="----=_NextPart_000_0042_01D5AE9A.F9895020"
>**X-Mailer: Microsoft Outlook 15.0**
>...

Is this somehow possible to make parsing less restrictive and allow empty IDs in corresponding headers?
I saw that the code relies on throwing an exception and then tries to access first element from a vector of IDs returned by the `mime::parse_many_ids()` method.

It probably would be better not to throw exception in case when ID is empty, and then check if the returned vector of IDs parsed by `mime::parse_many_ids()` is not empty. If it is, just consider using an empty ID later on. I could implement it in a PR if you're OK with this. Otherwise, messages sent by MS Outlook and some other clients can't be accessed by the library.

**Comment by karastojko** [comment]
Hopefully the [PR55](https://github.com/karastojko/mailio/pull/55) based on your [PR53](https://github.com/karastojko/mailio/pull/53) resolves the issue.
