### ISSUE TITLE
build error on mac and the message is: ld: library not found for -licudata

### ISSUE THREAD

**Issue by cfcz48** [karastojko/mailio#58]
message:ld: library not found for -licudata

output:
[ 33%] Building CXX object CMakeFiles/mailio.dir/src/pop3.cpp.o
[ 36%] Building CXX object CMakeFiles/mailio.dir/src/quoted_printable.cpp.o
[ 39%] Building CXX object CMakeFiles/mailio.dir/src/q_codec.cpp.o
[ 42%] Building CXX object CMakeFiles/mailio.dir/src/smtp.cpp.o
[ 45%] Linking CXX shared library libmailio.dylib
ld: library not found for -licudata
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libmailio.dylib] Error 1
make[1]: *** [CMakeFiles/mailio.dir/all] Error 2
make: *** [all] Error 2

platform: macos 11.1
cc:  clang 11.0.0
Target: x86_64-apple-darwin20.2.0
cmake: 3.19.2
make: 4.3

**Comment by karastojko** [comment]
Hi,
mailio does not use directly the ICU library, but you might have [the problem](https://stackoverflow.com/questions/50186021) with the regex library.
