### ISSUE TITLE
Define or delete MAILIO_EXPORT if it's not needed

### ISSUE THREAD

**Issue by mathbunnyru** [karastojko/mailio#59]
MAILIO_EXPORT seems to lack any definition.
At the same time some classes don't use it, which doesn't seem to be consistent.

For example:
`class dialog_ssl : public dialog`
`class q_codec : public codec`

**Comment by karastojko** [comment]
The macro is defined within `export.hpp` which is generated by the CMake script.

**Comment by mathbunnyru** [comment]
Oh, I see, thanks.

And what about places, which miss the macro?

**Comment by karastojko** [comment]
The macro is used in the case of dynamic/shared library, in case of the static one, you should not see an issue. The case with `q_codec` seems like a bug. Let me check for the `dialog` class, it is not meant to be out of the generated DLL, so I am not sure it should be exported at all.

**Comment by mathbunnyru** [comment]
Ok, thanks.

**Comment by karastojko** [comment]
Hopefully the code is cleaned with the latest [commit](https://github.com/karastojko/mailio/commit/45a1bbf40129df4c00e098d213bb9a63de4197f0). Also, the warning C4251 in MSVC should be fixed.

**Comment by mathbunnyru** [comment]
Thanks.
