### ISSUE TITLE
Empty Email Contents

### ISSUE THREAD

**Issue by JonathanBouligny** [karastojko/mailio#62]
```
msg.line_policy(mailio::codec::line_len_policy_t::VERYLARGE, mailio::codec::line_len_policy_t::VERYLARGE);
conn.fetch(2, msg);

std::cout << msg.subject() << std::endl;
std::cout << msg.content() << std::endl;
```
The email that i fetch gives me the subject line and its the correct subject line, however the contents are empty. The email has plenty of contents in it, images and text. I previously got the contents of another email to output, the email with the contents output had no attachment. The email without the contents output has an attachment.
**How can i get the correct contents of the message?**

**Comment by karastojko** [comment]
Hi, I believe you are dealing with the multipart message, thus you should fetch the parts and then print their content. Use the `mime::parts()` to get a MIME part.

**Comment by JonathanBouligny** [comment]
Yes that worked thank you.
