### ISSUE TITLE
Fail to build with msvc

### ISSUE THREAD

**Issue by ViniDalvino** [karastojko/mailio#65]
I tried to build the library with msvc using boost 1.75.0 and the using c++ 17. Here are the error that I am having: https://pastebin.com/f6nmsVm2

**Comment by karastojko** [comment]
Do you have OpenSSL installed?

**Comment by ViniDalvino** [comment]
I ended up solving the issue by dragging the library file to my visual studio solution as follow and it solved my problems: 
![image](https://user-images.githubusercontent.com/37189791/106814306-318a0100-6640-11eb-9162-b35ef2ca0223.png)
![image](https://user-images.githubusercontent.com/37189791/106814319-364eb500-6640-11eb-8b94-45deb18b7bbb.png)
