### ISSUE TITLE
Line handling

### ISSUE THREAD

**Issue by zsoltszakaly** [karastojko/mailio#67]
I try to send both plain e-mails with quoted content (received from another system) and HTML messages. The library cuts the lines in all cases. Questions/issues:
- If the quoted message has a \n in it, the system raises a mailio::codec_error. In all other mail systems I can send it, even if it is not the standard \r\n. Can this check somehow be switched off (it is hard to control what is in the quoted message, I want to forward)?
- I figured out the existence of the codec_error exception so it does not crash now (though does not send it either), but could not find a complete list of possible raised exception. Could it be listed somewhere in a "help" file? It would be important to prevent my whole program crashing from a yet unknown exception.
- In case of HTML the lines should not be cut at all. Where can I switch it off? Sometimes the line is simply longer and that should be OK.

Thanks,

**Comment by karastojko** [comment]
Hi,

- So you have a problem with message parsing or formatting?
- In the header files for each method you could find the exceptions might be thrown.
- Did you try to use the `codec::line_len_policy_t::VERYLARGE` for the line policy?

Regards,

**Comment by zsoltszakaly** [comment]
Hi,
Thanks for the reply.

- If I have     msg.content("blablabla\n"); then it raises an exception: mailio::codec_error. If it is msg.content("blablabla\r\n"); then it is sent OK. Since in my case I get the message content from another system and prefer not to start reformatting it, it would be nice if such a message could be sent. Maybe there is a parameter that can be set, not to be so strict with the check?

- I found the exceptions, thanks. I know it is extra work, but would be nice to have a help file where the exceptions are listed, also mentioning which one can be raised in what cases.

- Thanks for the hint. Now I added a new line:
    msg.line_policy(mailio::codec::line_len_policy_t::VERYLARGE, mailio::codec::line_len_policy_t::MANDATORY);
and now it does not break the lines; thanks. Honestly I do not fully understand what some of the constants do: I guess RECOMMENDED is the default and it splits the text into fixed length lines, VERYLARGE lets a max of 16k long line, but what does NONE and MANDATORY do? Also what are the valid options for the encoder and decoder line policies? Can all four (or are there other values too?) values be used for both directions? Again, a bit of help file would be a big help for a simple user like me.

Thanks again,
Zsolt

**Comment by karastojko** [comment]
Hi,
- Can you please run this example and tell me if you get an exception? Because I do not get it.
```
message msg;
msg.from(mail_address("your name", "you@address.com"));
msg.add_recipient(mail_address("your name", "you@address.com"));
msg.subject("Issue 67");
msg.content_transfer_encoding(mime::content_transfer_encoding_t::BASE_64);
msg.content_type(message::media_type_t::TEXT, "plain");
msg.content("blablabla\n");

smtps conn("smtp.yourhost.com", 587);
conn.authenticate("you@address.com", "your pass", smtps::auth_method_t::START_TLS);
conn.submit(msg);
```
- If you install Doxygen, you can generate documentation from the header files and see there the classes/methods descriptions.

- The line policy is about lines length in emails. The specification gives some numbers as `RECOMMENDED` and `MANDATORY`. In the practice, not all specification rules are followed, Thus, `NONE` and `VERYLARGE` are introduced to deal with emails with long lines.

Regards,
Tomislav

**Comment by zsoltszakaly** [comment]
Dear Tomislav,

Thanks a lot.
`    msg.content_transfer_encoding(message::mime::content_transfer_encoding_t::BASE_64);`
made the trick. If I have this line added then no exception is raised, if it is missing, it raises the exception or aborts if the exception is not caught.

I will also check the doc generation tool, but for now I found the exceptions I needed.

The line policy is still not very clear, but will study it in the source. What matters to me now, that VERYLARGE does the trick. My lines are transferred nicely.

So, I am closing the issue and thanks again for your prompt help.

Regards,
Zsolt
