### ISSUE TITLE
Documentation failing to build/install

### ISSUE THREAD

**Issue by UniversalBinary** [karastojko/mailio#68]
I am trying to build mailio on Ubuntu 20.10 however, there seems to be an issue with the documentation build.

I have ensured that the oxygen and dot commands are present on my system but the build fails, below is the last few lines before the failure.

[100%] Linking CXX executable smtps_simple_msg
make[2]: Leaving directory '/home/chris/Downloads/mailio/build'
[100%] Built target smtps_simple_msg
make[1]: Leaving directory '/home/chris/Downloads/mailio/build'
Install the project...
-- Install configuration: ""
CMake Error at cmake_install.cmake:41 (file):
  file INSTALL cannot find "/home/chris/Downloads/mailio/build/docs/html": No
  such file or directory.

make: *** [Makefile:86: install] Error 1

If I run cmake with -DMAILIO_BUILD_DOCUMENTATION=OFF everything builds and install OK.

**Comment by karastojko** [comment]
Hi,
Doxygen is required, not Oxygen.

**Comment by UniversalBinary** [comment]
Sorry, that was a typo. I meant to Doxygen.

**Comment by hilaolu** [comment]
Same problem.

**Comment by karastojko** [comment]
Please get the latest commit and try again.

**Comment by UniversalBinary** [comment]
Sorted, it is working now.

However, when you install the library under a system prefix, e.g. /usr/local, the documentation files are built and installed in /usr/local/docs. I am sure they should be placed in /usr/local/docs/mailio.

Otherwise, great. Please keep up the good work.
