### ISSUE TITLE
HTML Formatted Mail Problem

### ISSUE THREAD

**Issue by TaeZStkyoht** [karastojko/mailio#70]
Can this library supports html formatted mails? I've assigned a HTML formatted string to message content, however it has sent the exact HTML string not the interpreted version of HTML string.

**Comment by karastojko** [comment]
Just set the content type to text/html.

**Comment by TaeZStkyoht** [comment]
Ok I've tried text/html and didn't work. And I had also character encoding problem.
In the end I solved like that: `**msg.content_type(mime::media_type_t::TEXT, "html", "utf-8");**`
Not text/html but html. Because text/html didn't work properly.
For those who have problem like that, just use line I've written.
