### ISSUE TITLE
imap:: Getting e-mail subject and sender (from address)

### ISSUE THREAD

**Issue by Alx-prog** [karastojko/mailio#71]
Hi! I am trying to get subject and sender address strings of my first email in mailbox. My OS is Ubuntu 20.

imaps conn("imap.gmail.com", 993);
conn.authenticate(***", "***", imaps::auth_method_t::LOGIN);

message msg;
msg.line_policy(mailio::codec::line_len_policy_t::VERYLARGE, mailio::codec::line_len_policy_t::MANDATORY);

conn.fetch("inbox", 1, msg, false);  
// actual email data:
// from:    Google <no-reply@accounts.google.com>     
// subject: Critical security alert

std::string strAddress = msg.from_to_string();
std::cout << "Sender address:\t" << strAddress.length() << "\t" << strAddress.c_str() << endl; 
    
std::string strSubj = msg.subject();
std::cout << "Subject:\t" << strSubj.length() << "\t" << strSubj.c_str();

Here is the output
![output](https://user-images.githubusercontent.com/81563497/112826802-267aac80-9096-11eb-8d70-95856b6e861c.jpg)

How to get msg.subject_to_string()?
And one more thing is mismatching of sender addresses no-reply@accounts.google.com vs no-reply@google.com Why so?
Thank you.

**Comment by karastojko** [comment]
@Alx-prog  Hi,
Can you please paste the raw text instead of the image? Also, can you please write what the Sender and Subject strings are expected to be?

**Comment by Alx-prog** [comment]
Sender address:	71	=?UTF-8?Q?=EB=CF=CC=CC=C5=CB=D4=C9=D7_Gmail?= <mail-noreply@google.com>
Subject:	24	������ �� ������ � Gmail

Sender and Subject strings are expected to be
// from: Google no-reply@accounts.google.com
// subject: Critical security alert

**Comment by karastojko** [comment]
Can you please copy/paste the subject header from the MIME message? So, not the Cyrillic as you would expect here but something like
```
Subject: =?UTF-8?B?0JTQvtCx0YDQviDQv9C+0LbQsNC70L7QstCw0YLRjCDQsiBHbWFpbCE=?=\r\n
```

**Comment by Alx-prog** [comment]
MIME-Version: 1.0
Received: by 10.58.49.130; Tue, 22 Oct 2013 07:59:27 -0700 (PDT)
Date: Tue, 22 Oct 2013 07:59:27 -0700
Message-ID: <CA+X=YnUu262mApvZ3O7eypJrTA4sa6NBVs_NkkLEyR9Vo9+2Rg@mail.gmail.com>
Subject: Добро пожаловать в Gmail!
From: "Коллектив Gmail" <mail-noreply@google.com>
To: sms sender <snd2ph@gmail.com>
Content-Type: multipart/alternative; boundary=047d7bdc99cea3cac304e955a591

--047d7bdc99cea3cac304e955a591
Content-Type: text/plain; charset=KOI8-R
Content-Transfer-Encoding: base64

If I try to encode "Добро пожаловать в Gmail!" in far manager to UTF-8 I would get message "Editor contains characters, wich cannot be correctly translated using selected codepage. Continue?". And then I see "����� ���������� � Gmail!"

**Comment by karastojko** [comment]
You cannot use non ASCII characters for the subject in the MIME 7bit. Use the Q codec instead.

**Comment by Alx-prog** [comment]
Did you mean how to turn  "Добро пожаловать в Gmail!" into  "����� ���������� � Gmail!" ?

**Comment by karastojko** [comment]
No, I mean how did you generate the header ` Subject: Добро пожаловать в Gmail!`? That cannot be parsed with the library, but instead the header has to be like `Subject: =?UTF-8?B?0JTQvtCx0YDQviDQv9C+0LbQsNC70L7QstCw0YLRjCDQsiBHbWFpbCE=?=\r\n`?

**Comment by Alx-prog** [comment]
I just have followed that step in my gmail page:
https://electrictoolbox.com/gmail-view-raw-email-message/

And I copypasted from that.

**Comment by karastojko** [comment]
I do not know how Gmail internally encodes the MIME messages, but sending a mail with the same subject to Outlook and Dovecot shows that it is sent with the subject encoded as above (Q codec). However, I see that the subject is encoded in UTF8 when I am sending the message to myself on Gmail. It's possible that Gmail uses UTF8 when the message stays within Gmail servers.
In your case, the library will report an exception for the header like `Subject: Добро пожаловать в Gmail!` and should succeed for `Subject: =?UTF-8?B?0JTQvtCx0YDQviDQv9C+0LbQsNC70L7QstCw0YLRjCDQsiBHbWFpbCE=?=`. I am not sure that there exists solution for your problem, since I do not believe that it is possible to force an encoding from the web interface.

**Comment by Alx-prog** [comment]
Ok. Then let's close this issue.
