### ISSUE TITLE
Why is message::_date_time a shared pointer?

### ISSUE THREAD

**Issue by sabelka** [karastojko/mailio#73]
Is there a particular reason why `message::_date_time` is a shared pointer?

**Comment by karastojko** [comment]
Seems it is the relic of some old decisions. So far the tests look good when the shared pointer is dropped off. Let me test few more things and if everything is fine I will push the change.

**Comment by karastojko** [comment]
Should be fixed with the latest [commit](https://github.com/karastojko/mailio/commit/1c2011da2b2967a7f055e96c70b492030d6c2830).
