### ISSUE TITLE
CMake Version 3.12

### ISSUE THREAD

**Issue by jchampeau** [karastojko/mailio#75]
Can the CMake minimum version be lowered to 3.12?

I was using the Conan package successfully for a portable application on Windows and Linux.  However the embedded Linux build will not work just because of the CMake version restriction.  I am limited to CMake 3.12 for the embedded SDK.   I was able to clone the library and  build it by changing the cmake_minimum_required to 3.12.

It looks like the CMake minimum version was changed from 3.9 to 3.16 in version 0.19.  But I'm not sure if that is necessary as I was able to get it to work with CMake 3.12 on version 0.20 of the library.

For now, I will have to build from the cloned source with the modified CMake file.  But it would be nice to use the Conan package.

**Comment by karastojko** [comment]
By looking into [versions](https://github.com/Kitware/CMake/blob/v3.12.0/Modules/FindBoost.cmake) it is declared that the latest supported Boost version is 1.68. CMake 3.12 would require downgrade the version of Boost, and the goal is to periodically catch up with the latest Boost releases. Indeed, I tried CMake 3.12/Boost 1.71 on Windows and it fails.
Which version of Boost you are using for your successful case?
