### ISSUE TITLE
HTML Email with an attachment.

### ISSUE THREAD

**Issue by Aamir1313** [karastojko/mailio#81]
Hi, I am having issues sending an html email with an attachment. The following code sends the email body (emailContent) as a text string. I also played around by moving the attach call before the content_type call and it seemed to hang on the submit method.

msg.content_transfer_encoding(mime::content_transfer_encoding_t::BASE_64);
msg.content_type(message::media_type_t::TEXT, "html", "utf-8");
msg.content(emailContent);

std::ifstream ifs1(fileName);
msg.attach(ifs1, fileName, message::media_type_t::IMAGE, "png");

smtps conn(fromEmailServerSetting, fromEmailPortSetting);
conn.authenticate(fromEmailSetting, fromEmailPwdSetting, smtps::auth_method_t::START_TLS);
conn.submit(msg);

**Comment by karastojko** [comment]
I have a test which sends an HTML content content with a png file, everything works fine. In order to better understand the issue, are you sure that the authentication finished properly? Are you using some of the public email servers?
