### ISSUE TITLE
html content rendered strangely

### ISSUE THREAD

**Issue by georgbuechner** [karastojko/mailio#83]
Hello, first of all: thank you very much for writing, maintaining and providing  this easy to use library!

I am currently experiencing a strange error: when printing f.e. the following text:
```
<!DOCTYPE html><html><head><meta charset='utf-8'/><meta name='viewpoint' content='width=device-width, initial-scale=1.0'/></head><body><div>Dear User, <br><br>for your controller <i>wintergarten</i> the following alarms where triggered: <br>- <i>Low RH Night</i>: 9.000000 % RH.<br><br><br>Sincerely<br><br>(This e-mail was sent, as you wished to be informed about changes in your email-adress and/or alarms)</div></body></html>
```

The E-Mail gets sent looking like this: 
```
Dear User,
br>for your controller wintergarten the following alarms where triggere d:
- Low RH Night: 9.000000 % RH.


Sincerely

(This e-mail was sent, as you wished to be informed about changes in your email-adress and/or alarms)
```

Where do the spaces (`triggere d`),  come from and how come some html-tags are shown?  Am I doing something wrong? I'm setting the content using the following command: `msg.content_type(mailio::message::media_type_t::TEXT, "html", "utf-8");`

If I copy and past the above email content in a HTML-file and open it with Firefox, the text is shown as expected and when viewing the source, Firefox shows no errors.  It could however also be, that I just don't know how to create mails with HTML-content :D If this is the case, I apologize and would be grateful for for getting pointed in the right direction.

OS: Manjaro (Linux)
Version: mailio/0.20.0 (conan)

Let me know if you need any other information.

**Comment by karastojko** [comment]
Hi, currently mailio does not support 8bit encoding. Thus, you have to use some other mechanism to transport the characters out of the 7bit. Set for instance `msg.content_transfer_encoding(mime::content_transfer_encoding_t::BASE_64);` and you should see the message correctly formatted.

**Comment by georgbuechner** [comment]
Thanks a lot, using `msg.content_transfer_encoding(mime::content_transfer_encoding_t::BASE_64);` solved the problem. 
New code looks like this: 
```
mailio::message msg;
msg.from(mailio::mail_address("MyUser", email_address_));
msg.subject(full_subject);
msg.content_transfer_encoding(mailio::mime::content_transfer_encoding_t::BASE_64);
msg.content_type(mailio::message::media_type_t::TEXT, "html", "utf-8");
msg.content(full_content);
```
