### ISSUE TITLE
cannot fetch list of messages from GMail

### ISSUE THREAD

**Issue by elcuco** [karastojko/mailio#86]
Using mailio 0.20.0 (from connan), on OXS/AppleSilicon. I am connected to a gmail server, using application output. 

I am able to get folder list, statistics for each folder - but fetching the content of the lists fails. Its hard to debug, and no exact documentation about this code path. What am I missing?

``` C++
    try {
        std::list<mailio::imap::messages_range_t> range;
        std::map<unsigned long, mailio::message> found;
        // I am requesting range, right? 
        bool uids = false;
        bool headers_only = true;
        // max, is the amount of files on the folder/box. As reported by `statistics()` 
        // tried using also "0" - same result
        range.push_back({1, max});

        // a shared_ptr<mailio::imaps> 
        this->connection->fetch(range, found, uids, headers_only);
        std::cout << "Found messages: " << found.size() << std::endl;
    } catch  (imap_error e) {
        std::cerr << "fetch(" <<  folder_name << ", [1," << max << "] ) failed ";
        std::cerr << e.what();
        std::cerr << std::endl;
        return ;
    }
```

EDIT:
This code produces another interesting issue (I did not select the folder, and range was probably back):
``` C++
        std::list<mailio::imap::messages_range_t> range;
        std::map<unsigned long, mailio::message> found;
        mailio::codec::line_len_policy_t line_policy = mailio::codec::line_len_policy_t::VERYLARGE;
        bool uids = false;
        bool headers_only = true;
        range.push_back({1, {max}});
        this->connection->select( std::list<std::string>({folder_name}), true);
        this->connection->fetch(range, found, uids, headers_only, line_policy);
        std::cout << "Found messages: " << found.size() << std::endl;
``` 

Now the code crashes at runtime with `terminating with uncaught exception of type mailio::mime_error: Format failure of the header value... `. Here I see an email. How can i debug this? Does this library have any way add logs (besides nodifying the code it self?).

**Comment by karastojko** [comment]
Either you have to select a folder before fetching or use the fetch with the given folder name. Thus, the second approach is the correct way. However, it seems there is an issue with the email header. Can you please paste it here with the mangled sensitive info?
There is no logging (the planned feature), also I will put more descriptive error messages.

**Comment by elcuco** [comment]
Sure - how can I print such logs?
I am using connan, so I don't have direct access to the logs, so I assume using FetchContent and modifying the code is my only way :)

**Comment by karastojko** [comment]
Since it reports the problem with the header value at the [regex](https://github.com/karastojko/mailio/blob/cc887a7808d9c55e07c8a7503c7ae2e2d7485120/src/mime.cpp#L719), you could also add the whole `header_line` to be stored into the exception message, and then print it. It would be interesting to see what is the header value which produces the problem, and then to check whether it conforms to the standard or it's a mailio bug.

**Comment by elcuco** [comment]
This line fails:  `From: מערכת ההזדהות הממשלתית <DoNotReply@tehila.gov.il>` 

Which means `const regex mime::HEADER_VALUE_REGEX{R"(([a-zA-Z0-9\ \!\"#\$%&'\(\)\*\+\,\-\./:;\<=\>\?@\[\\\]\^\_`\{\|\}\~]+))"};` is wrong - it only takes under consideration Latin1. For any non-Latin1 friendly name this fails.

**Comment by karastojko** [comment]
Is the line `From: מערכת ההזדהות הממשלתית <DoNotReply@tehila.gov.il>` extracted from the email source or you pasted it here from the email client as displayed?

**Comment by elcuco** [comment]
Its the output from line 707:

```
    if (!regex_match(header_value, m, HEADER_VALUE_REGEX))
        throw mime_error("Format failure of the header value `" + header_value + "`." +  " - " + header_line);
```

The exact message I see on stderr is:
```
libc++abi: terminating with uncaught exception of type mailio::mime_error: Format failure of the header value `מערכת ההזדהות הממשלתית <DoNotReply@tehila.gov.il>`. - From: מערכת ההזדהות הממשלתית <DoNotReply@tehila.gov.il>
```

I tried setting line 101 to this (added `\\w` which should be a word character) but this is still fialing:
```
const regex mime::HEADER_VALUE_REGEX{R"(([\\wa-zA-Z0-9\ \!\"#\$%&'\(\)\*\+\,\-\./:;\<=\>\?@\[\\\]\^\_`\{\|\}\~]+))"};
```

**Comment by karastojko** [comment]
Currently mailio works only with 7bit MIME format. Thus, UTF8 characters in headers are not recognized. As you can see, one of the problems is using regular expressions with non Latin characters. In order to use UTF8 in headers with mailio, it has to be encoded with Base64 or Q encoding.

**Comment by elcuco** [comment]
That affectively renders mailio useless in real world. 

How about splitting that line using ":" ? Everything before is the header name, and after is the value. 
I assume you parse emails using regex right? What else needs to be changed in order to fix the above issue?

**Comment by karastojko** [comment]
Most of the email clients use the Q encoding in headers. If you use plain UTF8, then it's of no use to you. The email body is not parsed with regex (check the source code). In case you need to parse 8bit headers, just write a small state machine as for the address list parsing, for instance.

**Comment by karastojko** [comment]
@elcuco 
Perhaps the latest [commit](https://github.com/karastojko/mailio/commit/9b551f4177196235a4dde4d1dad87c7afb2c52cf) can help you.

**Comment by elcuco** [comment]
Sorry for late reply, I am now facing another problem (again, in GMail):

```
terminate called after throwing an instance of 'mailio::message_error'
  what():  Line policy overflow in a header. (86)
```

One of the headers is too large (86 bytes) and the parser fails.

**Comment by karastojko** [comment]
For the line policy you could use the `mime::line_policy()`. There is no need to change the constructor of the `message` constructor.

I don't see you have set the range, it is an empty list. So, I would do something like
```
    list<imap::messages_range_t> ranges;
    ranges.push_back(imap::messages_range_t(1, 100)); // the missing criteria!
    std::map<unsigned long, message> found_messages;
    conn.fetch(ranges, found_messages, false, false, codec::line_len_policy_t::NONE);
```
That's why the server response does not have the UID value. However, the empty range list should be also reported by `imap` as a problem. Thanks for pointing this out.

**Comment by karastojko** [comment]
The empty range problem is fixed with the latest [commit](https://github.com/karastojko/mailio/commit/67f8d23b860b62d3ae656056926b0d95b2a6d1c2).

**Comment by elcuco** [comment]
yap, got it.  I manage to get it works, without changes. Still finding some corner cases, and I am looking for some APIs... I will open other PRs/issues as found. Thanks for the hard help!
