### ISSUE TITLE
Executable on windows is large

### ISSUE THREAD

**Issue by kjrmatt** [karastojko/mailio#92]
I built the source using MinGW and compiled some example codes in the "examples" folder. Everything works, although the executables are 12 MB -- this is large for an executable. I noticed that everything is built statically. I wonder if there is a way to link the dependencies dynamically?

**Comment by karastojko** [comment]
In the `CMakeLists.txt` instead of the line
```
add_library(${PROJECT_NAME} ${project_sources} ${project_headers})```
```
use
```
add_library(${PROJECT_NAME} SHARED ${project_sources} ${project_headers})
```
