### ISSUE TITLE
Static folder delimiter

### ISSUE THREAD

**Issue by canyone2015** [karastojko/mailio#93]
When changing the imap server, the delimiter remains the same, although it obviously must change.

Please, remove static folder delimiter in imap::folder_delimiter() method:
```cpp
static string delimiter;
```
and create field to store the delimiter.

**Comment by canyone2015** [comment]
Quick fix:
1. Remove this line (src/imap.cpp):
```cpp
static string delimiter;
```
2. Add this line to the end of imap class (include/mailio/imap.hpp):
```cpp
    /**
    Folder delimiter
    **/
    std::string delimiter;
```

**Comment by karastojko** [comment]
Fixed with the latest [commit](https://github.com/karastojko/mailio/commit/e014f076c664e61f61752477fa97b5d7612cc313). I have added you to the Contributors section.
